# Generated by Django 5.0.6 on 2024-07-02 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumego', '0002_data_solution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTsumego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('solved_date', models.DateTimeField(blank=True, null=True)),
                ('tsumego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsumego.data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='users',
            field=models.ManyToManyField(through='tsumego.UserTsumego', to=settings.AUTH_USER_MODEL),
        ),
    ]
