# Generated by Django 5.0.6 on 2024-07-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumego', '0003_usertsumego_data_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertsumego',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
